### ISSUE TITLE
Tourist - Crash when using Squadron Command Actions

### ISSUE THREAD

**Issue by tommadness** [ascclemens/plugin-issues#56]
When engaging in Squadron Command Missions with Tourist v1.2.11 installed, using the "Disengage" action causes a crash with the following exception:

```
System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at Tourist.Markers.RemoveVfx(UInt16 index) in /work/repo/Tourist/Markers.cs:line 35
at Tourist.GameFunctions.OnVistaUnlock(UInt16 index, Int32 a2, Int32 a3) in /work/repo/Tourist/GameFunctions.cs:line 51
```

Disabling Tourist stops the crashes.

I have repro'd this on Wanderer's Palace and Brayflox Longstop (Hard).

Let me know either here or in the Dalamud Discord (Tommadness#9734) if you need any further info.

**Comment by ascclemens** [comment]
Knew I should've checked the sigs and offsets more thoroughly

**Comment by ascclemens** [comment]
Fixed
