### ISSUE TITLE
Alt+Click Examine Broken with PTom 6.2 update.

### ISSUE THREAD

**Issue by Lockehart** [ascclemens/plugin-issues#8]
Attempting to alt+click a name on the list to examine them currently crashes the plugin.  Have to disable and reenable ptom or relog for it to be useable again.

**Comment by reiichi001** [comment]
Sample exception stack from goatplace feedback channel:
```
System.InvalidOperationException: Could not find signature for Examine function
   at XivCommon.Functions.Examine.OpenExamineWindow(UInt32 objectId)
   at PeepingTom.PluginUi.AddEntry(Targeter targeter, GameObject obj, Boolean& anyHovered, ImGuiSelectableFlags flags) in /work/repo/Peeping Tom/PluginUi.cs:line 0
   at PeepingTom.PluginUi.ShowMainWindow() in /work/repo/Peeping Tom/PluginUi.cs:line 424
   at PeepingTom.PluginUi.Draw() in /work/repo/Peeping Tom/PluginUi.cs:line 79
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 501
   ```

**Comment by ascclemens** [comment]
Fixed.
